############### Runs with optimized hparams #################
# this task is already done as part of the hparam opt (see hnppo_lever_long)
hnppo_lever_0:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 2e-2
    clip-param: 0.35
    max-grad-norm: 1e-4
    task-id: 0
    network-width: 80
    network-depth: 3
    num-env-steps: 12000000
    entropy-coef: 1e-4
    beta: 5e-3  # does not matter for task 0
    te-dim: 16
    save-name: hnppo-lever_long
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook/
  flags-dest: args

# Note: the commented out args are irrelevant for subsequent tasks, since they are determined by the pretrained
# model from the first task
hnppo_pull_1:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 2e-2
    clip-param: 0.35
    max-grad-norm: 1e-4
    task-id: 1
    # network-width: 80
    # network-depth: 3
    num-env-steps: 12000000
    entropy-coef: 1e-4
    beta: 5e-3
    # te-dim: 16
    save-name: hnppo-pull
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook/
  flags-dest: args

# Using Doorgym default args instead of ones optimized for the lever task. These worked before on pull doors too.
hnppo_pull_1_defaultargs:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 1e-3
    clip-param: 0.2
    max-grad-norm: 1e-4
    task-id: 1
    # network-width: 80
    # network-depth: 3
    num-env-steps: 12000000
    entropy-coef: 1e-2
    beta: 5e-3
    # te-dim: 16
    save-name: hnppo-pull
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook/
  flags-dest: args

hnppo_lever_left_2:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 1e-2  # 2e-2 yielded NaN error after some iterations
    clip-param: 0.35
    max-grad-norm: 1e-4
    task-id: 2
    #network-width: 80
    #network-depth: 3
    num-env-steps: 12000000
    entropy-coef: 1e-4
    beta: 5e-3
    #te-dim: 16
    save-name: hnppo-lever_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_left/
  flags-dest: args


############### Runs with old, non-optimized hparams (ppo-hn10) #################
series2_hnppo_pull_0:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 0
    num-env-steps: 12000000
    beta: 5e-3
    save-name: hnppo-pull
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook/
  flags-dest: args

series2_hnppo_pull_left_1:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 1
    num-env-steps: 12000000
    beta: 5e-3
    save-name: hnppo-pull_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook_left_fixed/
  flags-dest: args

series2_hnppo_lever_2:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 2
    num-env-steps: 12000000
    beta: 2e-3
    save-name: hnppo-lever
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook/
  flags-dest: args

series2_hnppo_lever_left_3:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 3
    num-env-steps: 12000000
    beta: 2e-3
    save-name: hnppo-lever_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_left/
  flags-dest: args

series2_hnppo_lever_push_4:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 4
    num-env-steps: 24000000
    beta: 1e-3
    save-name: hnppo-lever_push
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_push/
  flags-dest: args

######series 3: even lower beta, since 0.001 did still not show any forgetting###########
# Also running deterministically
series3_hnppo_pull_0:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 0
    num-env-steps: 12000000
    beta: 5e-4
    save-name: hnppo-pull
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series3_hnppo_pull_left_1:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 1
    num-env-steps: 12000000
    beta: 5e-4
    save-name: hnppo-pull_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook_left_fixed/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series3_hnppo_lever_2:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 2
    num-env-steps: 12000000
    beta: 5e-4
    save-name: hnppo-lever
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series3_hnppo_lever_left_3:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 3
    num-env-steps: 12000000
    beta: 5e-4
    save-name: hnppo-lever_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_left/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

######series 4: back to higher beta but with determinism ###########
series4_hnppo_pull_0:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  # will reuse this run from series3 since beta has no effect for first run

series4_hnppo_pull_left_1:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 1
    num-env-steps: 12000000
    beta: 1e-3
    save-name: hnppo-pull_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook_left_fixed/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series4_hnppo_lever_2:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 2
    num-env-steps: 12000000
    beta: 1e-3
    save-name: hnppo-lever
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series4_hnppo_lever_left_3:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 3
    num-env-steps: 12000000
    beta: 1e-3
    save-name: hnppo-lever_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_left/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series4_hnppo_lever_push_4:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 4
    num-env-steps: 12000000
    beta: 1e-3
    save-name: hnppo-lever_push
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_push/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series4_hnppo_lever_push_left_5:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 5
    num-env-steps: 12000000
    beta: 1e-3
    save-name: hnppo-lever_push_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_push_left/
    seed: 1
    cuda-deterministic: True
  flags-dest: args