######series 9: same hparams as series 4, but no regularization in hnet ###########
series9_hnppo_pull_0:
  # will reuse this run from series3 since beta has no effect for first run
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 0
    num-env-steps: 12000000
    beta: 0
    save-name: hnppo-pull
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series9_hnppo_pull_left_1:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 1
    num-env-steps: 12000000
    beta: 0
    save-name: hnppo-pull_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/pull_blue_floatinghook_left_fixed/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series9_hnppo_lever_2:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 2
    num-env-steps: 12000000
    beta: 0
    save-name: hnppo-lever
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series9_hnppo_lever_left_3:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 3
    num-env-steps: 12000000
    beta: 0
    save-name: hnppo-lever_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_left/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series9_hnppo_lever_push_4:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 4
    num-env-steps: 24000000
    beta: 0
    save-name: hnppo-lever_push
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_push/
    seed: 1
    cuda-deterministic: True
  flags-dest: args

series9_hnppo_lever_push_left_5:
  main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
  flags:
    env-name: doorenv-v0
    algo: hnppo
    num-processes: 8
    lr: 0.005
    clip-param: 0.3
    max-grad-norm: 1e-4
    task-id: 5
    num-env-steps: 24000000
    beta: 0
    save-name: hnppo-lever_push_left
    world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook_push_left/
    seed: 1
    cuda-deterministic: True
  flags-dest: args