- operations:
    ########### Misc experiments that don't fit anywhere else. ###########

    # Test with the floatinghook robot again - maybe this one can open lever doors
    hooktest_lever:
      main: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/main
      flags:
        env-name: doorenv-v0
        algo: hnppo
        num-processes: 8
        task-id: 0
        clip-param: 0.3
        max-grad-norm: 1e-4
        lr: 1e-2
        num-env-steps: 4000000
        save-name: hnppo-hooktest-task0-lever
        world-path: /home/philemon.schoepf/schoepf-bachelor-thesis/DoorGym/world_generator/world/lever_blue_floatinghook/
      flags-dest: args
